name: Build Pipeline
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coding-standard:
    name: "Coding Standard"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        php: [ "7.4" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: ds

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check codestyle
        run: vendor/bin/phpcs --standard=PSR12 src/ tests/

  unit-tests:
    name: "Unit Tests"
    runs-on: "${{ matrix.os }}"
    continue-on-error: "${{ matrix.experimental }}"
    strategy:
      fail-fast: false
      matrix:
        php: [ "7.4", "8.0", "8.1", "8.2" ]
        os: [ "ubuntu-latest" ]
        experimental: [ false ]

    steps:
      - name: Install packages
        run: sudo apt-get install -y aspell aspell-en

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: ds

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader ${{ matrix.composer-options }}

      - name: Execute tests
        run: vendor/bin/phpunit --colors=always --coverage-text
